### ISSUE TITLE
I really hate this 

### ISSUE THREAD

**Issue by bitmold** [Kreyren/transgenders#1]
I genuinely can't tell if this is some really fucked up joke or the most misguided guide that I have ever encountered being both intensely offensive and inaccurate. If you at all were serious about wanting to help trans people in any way you should completely take this down because it is without a doubt beyond irredeemable. If this is some sick joke, which it sure sounds like, fuck off 

EDIT(Krey): Removed the '#' prefix so that the message is readable from the phone.

**Comment by Kreyren** [comment]
It's not meant to be a joke.

Was created based on:
- My experience with transgenders
- Informations provided from transgenders
- My own research

It was made, because in my experience and environment people are not educated about the subject and doesn't know how to behave around transgenders which usually results in questions like mentioned in https://github.com/Kreyren/Transgenders#your-inapropriate-questions-answered and with this project i am trying to reduce the amount of these questions since it doesn't seem to be good for the mental health of transgenders.

Please be more specific about what you hate about it and i will be happy to update it or sent a merge request ^-^

**Comment by Kreyren** [comment]
FWIW i am in contact with transgenders multiple times a week and so far this seems to reduce the amount of inappropriate questions and improve their acceptance in general community.

**Comment by Kreyren** [comment]
Assignment removed assuming `invalid` for lack of informations provided for this to be actionable.

Will reopen if required informations are provided.

---

@bitmold I would appreciate if you told me what made you to hate this in case it could be rephrased ^-^
